openapi: 3.0.0
info:
  title: Integrated RAG Chatbot API
  description: API for the Integrated RAG Chatbot that allows users to ask questions about book content
  version: 1.0.0
paths:
  /query:
    post:
      summary: Submit a query about book content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
              properties:
                question:
                  type: string
                  description: The question to ask about the book content
                  example: "What is the main theme of this book?"
                selected_text:
                  type: string
                  description: Optional text selected by the user to limit the context
                  example: "This is the specific text the user selected..."
                book_id:
                  type: string
                  description: The ID of the book to query
                  example: "book-123"
      responses:
        '200':
          description: Successful response with the answer
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The answer generated by the system
                    example: "The main theme of this book is..."
                  sources:
                    type: array
                    items:
                      type: string
                    description: IDs of the content chunks used to generate the answer
                    example: ["chunk-1", "chunk-2"]
                  mode_used:
                    type: string
                    description: The mode used for the query
                    enum: [full_book, selected_text]
        '400':
          description: Bad request when required fields are missing
        '500':
          description: Internal server error
  /health:
    get:
      summary: Check the health of the service
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
  /books:
    get:
      summary: List available books
      responses:
        '200':
          description: List of available books
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Unique identifier for the book
                    title:
                      type: string
                      description: Title of the book
                    author:
                      type: string
                      description: Author of the book
  /books/{book_id}:
    get:
      summary: Get details about a specific book
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details about the specified book
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  author:
                    type: string
                  content_preview:
                    type: string
                    description: A short preview of the book content
        '404':
          description: Book not found